### ISSUE TITLE
引入RongIMLib-cs.min.js 一直报错

### ISSUE THREAD

**Issue by SnowBeatRain** [rongcloud/websdk-demo#11]
按照文档引入：<link rel="stylesheet" href="cs.min.css">

<script src="../RongIMLib-cs.min.js"></script>
<script src="//cdn.ronghub.com/RongIMVoice-2.2.4.min.js"></script>
<script src="cs.min.js"></script>
结果提示Uncaught TypeError: Cannot read property 'length' of undefined
![dk6ojbg_ iv4rn0g 5 0y 0](https://user-images.githubusercontent.com/26265459/50753250-252df100-128c-11e9-9f6f-e9ca896a156a.png)
![pqu r xb7_nvx s5vef1 d](https://user-images.githubusercontent.com/26265459/50753254-2c54ff00-128c-11e9-8a3f-91f61fae4683.png)

**Comment by YongHao0** [comment]
按以下思路排查下：
1.  是否 README.md 进行集成
2. 页面节点是否挂载成功，资源是否全部引入
3. 客服服务是否开通（开通位置：融云开发者控制台->运营管理->客服管理）
4. 从相关报错位置打断点, 查看语法报错原因
