### ISSUE TITLE
websdk: RongCallLib.commandWatch命令监听问题

### ISSUE THREAD

**Issue by lantian1024** [rongcloud/websdk-demo#13]
有以下场景：
用户A打开页面，向用用户B发送视屏邀请（此时用户B没有打开页面）；
然后，用户B打开页面，控制台显示有onRecrived消息过来，但是没有触发RongCallLib.commandWatch，请问这是bug还是设计就这样？
提议：这种场景触发回调会更好
![image](https://user-images.githubusercontent.com/18543726/56026086-02592000-5d46-11e9-872b-a70dc23d2013.png)

**Comment by YongHao0** [comment]
> 有以下场景：
> 用户A打开页面，向用用户B发送视屏邀请（此时用户B没有打开页面）；
> 然后，用户B打开页面，控制台显示有onRecrived消息过来，但是没有触发RongCallLib.commandWatch，请问这是bug还是设计就这样？
> 提议：这种场景触发回调会更好
> ![image](https://user-images.githubusercontent.com/18543726/56026086-02592000-5d46-11e9-872b-a70dc23d2013.png)

设计如此. 用户 A 发消息后, 用户 B 才登陆, 也就是说用户 B 收到的是离线消息, 此时是不会触发 commandWatch 回调的
