### ISSUE TITLE
uni 在app模式下报错 h5正常连接

### ISSUE THREAD

**Issue by 13725102796** [rongcloud/websdk-demo#14]
[ERROR] : Page is not constructed because it is not found.

**Comment by shuise** [comment]
web sdk 不支持混合开发，移动端有专门的 sdk

**Comment by 13725102796** [comment]
> web sdk 不支持混合开发，移动端有专门的 sdk

那混合开发要怎么弄

**Comment by shuise** [comment]
混合开发是 远程 SDK 做底层，加 web 做 UI 层

**Comment by 13725102796** [comment]
> 混合开发是 远程 SDK 做底层，加 web 做 UI 层

有没有案例或者相关资料呀！大佬

**Comment by shuise** [comment]
官方有提供 RN：https://www.rongcloud.cn/docs/react_native_imlib.html

**Comment by 13725102796** [comment]
> 官方有提供 RN：https://www.rongcloud.cn/docs/react_native_imlib.html

rn的估计不合适
