### ISSUE TITLE
vue-cli3.0引入报错

### ISSUE THREAD

**Issue by airzhanglin** [rongcloud/websdk-demo#15]
![image](https://user-images.githubusercontent.com/16433124/61680011-bbae9500-ad3a-11e9-884f-0ebdb03f06cd.png)
一直报这个错误，文件是从sdk使用demo中下载的

**Comment by shuise** [comment]
用的是那种包管理机制？是否按照对应方式加载的 sdk？

**Comment by airzhanglin** [comment]
> 用的是那种包管理机制？是否按照对应方式加载的 sdk？
使用的是require方式进来的

**Comment by shuise** [comment]
https://github.com/rongcloud/websdk-demo/tree/master/vue-cli

**Comment by YongHao0** [comment]
> > 用的是那种包管理机制？是否按照对应方式加载的 sdk？
> > 使用的是require方式进来的
Vue CLI Demo 参考: https://github.com/rongcloud/websdk-demo/tree/master/vue-cli
