### ISSUE TITLE
window下挂载的RongIMClient无效

### ISSUE THREAD

**Issue by ZhangAixue** [rongcloud/websdk-demo#16]
window下挂载的RongIMClient无效，一定要使用RongIMLib.RongIMClient

**Comment by YongHao0** [comment]
> window下挂载的RongIMClient无效，一定要使用RongIMLib.RongIMClient

您具体使用的哪个版本的 SDK ? 是如何引入的, 可以把代码贴一下
引入方式您可参考下文档:

**Comment by YongHao0** [comment]
> > window下挂载的RongIMClient无效，一定要使用RongIMLib.RongIMClient
> 
> 您具体使用的哪个版本的 SDK ? 是如何引入的, 可以把代码贴一下
> 引入方式您可参考下文档:

https://docs.rongcloud.cn/im/imlib/web/init/#import
