### ISSUE TITLE
如何获取实时视频流的信息，包括分辨率、丢包、抖动、占用带宽等参数

### ISSUE THREAD

**Issue by 13701138894** [rongcloud/websdk-demo#17]
如何获取实时视频流的信息，包括分辨率、丢包、抖动、占用带宽等参数

**Comment by 13701138894** [comment]
web端

**Comment by FrancisLL** [comment]
分辨率：video 节点的 videoHeight 和 videoWidth 属性
丢包、抖动、占用带宽 ：可使用 wireshark 抓包工具，或 Chrome 浏览器自带工具 chrome://webrtc-internals/
