### ISSUE TITLE
佳信客服无法弹出聊天界面

### ISSUE THREAD

**Issue by 15380831711** [rongcloud/websdk-demo#19]
佳信客服无法弹出聊天界面，只打印“客服初始化成功”。 
另外一个客服sobot，好像是智齿客服，可以进入聊天界面，代码都是刚拉的最新的。融云后台目前好像不支持智齿客服了吗？

**Comment by FrancisLL** [comment]
1、佳信客服无法弹出聊天页面问题，提供一下排查思路：
是否 README.md 进行集成，页面节点是否挂载成功，资源是否全部引入，客服服务是否开通（开通位置：融云开发者控制台->运营管理->客服管理）
2、是否支持智齿客服：
以融云开发者后台通知为准
