### ISSUE TITLE
在Electron-vue生成的项目里，引入sdk，不能成功connect

### ISSUE THREAD

**Issue by arthasshi** [rongcloud/websdk-demo#8]
1、通过初始化 electron-vue 项目后，在 index.ejs 中引入融云 WebIMSDK （ RongIMLib-2.3.2.js ） 2、按照融云 demo 中的初始化方法 startInit 去初始化 3、初始化方法执行了，打印 RongIMLib 和 RongIMClient 对象都有值，但是没有走 RongIMClient.connect 开始连接的方法，也没有任何报错信息

测试一：自己新建了一个 vue-cli 脚手架的网页项目，在 index.html 中引入 RongIMLib-2.3.2.js ，并实现 startInit 初始化方法，运行程序提示连接成功，执行了 RongIMClient.connect，表明已正确集成了 SDK 
测试二：自己新建一个纯 Electron 的项目，按照步骤引入 sdk，连接成功

疑问：为什么 electron-vue 项目中会集成失败？

**Comment by JsoonLi** [comment]
@arthasshi 同样遇到这个问题，请问下解决没有？

**Comment by JsoonLi** [comment]
已解决！

**Comment by arthasshi** [comment]
解决了？我没解决 放弃了

**Comment by JsoonLi** [comment]
@arthasshi 主要是RongIMLib.RongIMClient.Protobuf没有值。我下载到本地引用的。

**Comment by shuise** [comment]
https://github.com/rongcloud/websdk-demo/tree/master/electron 这不是有现成的示例么？
